### ISSUE TITLE
Creación de la base de datos

### ISSUE THREAD

**Issue by JorRoFe** [Arquisoft/citizensLoader4b#6]
Se encargará de la creación de la BBDD, ademas de sus métodos para insertar datos.

**Comment by RaulG89** [comment]
A la espera de respuesta de los compañeros del 4B2.

**Comment by RaulG89** [comment]
Ya sincronizados con grupo 4B2, implementando.

**Comment by RaulG89** [comment]
Creada implementación base de datos, falta reporte.
